# Generated by Django 3.2.10 on 2022-02-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinationtype',
            name='paper_type',
            field=models.SlugField(choices=[('board', 'board'), ('university', 'university')], help_text='Different levels of schools and colleges like Board and University', max_length=12),
        ),
        migrations.AlterField(
            model_name='governingbody',
            name='education',
            field=models.ManyToManyField(to='nouns.ExaminationType'),
        ),
        migrations.DeleteModel(
            name='PaperType',
        ),
    ]
