# Generated by Django 3.2 on 2021-06-01 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=10)),
                ('issues', models.TextField()),
                ('isuue_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
