# Generated by Django 3.2 on 2021-12-05 14:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
