# Generated by Django 3.2.10 on 2022-02-03 19:50

import cloudinary_storage.storage
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import question_papers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nouns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_year', models.DateField(help_text='year when the question paper was released')),
                ('paper_title', models.CharField(help_text='title of the paper', max_length=100)),
                ('paper_doc', models.FileField(help_text='The actual paper documnet', max_length=200, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=question_papers.models.update_filename_and_path_dev, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('complete_ref', models.CharField(blank=True, help_text='a complete reference which is used in search', max_length=800)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('course_name', models.ForeignKey(help_text='Name of the course', on_delete=django.db.models.deletion.CASCADE, to='nouns.course')),
                ('education_type', models.ForeignKey(help_text='Different education types like SSLC, PUC,Degree, Engineering or Diploma', on_delete=django.db.models.deletion.CASCADE, to='nouns.examinationtype')),
                ('governing_body', models.ForeignKey(help_text='The authority who governs that Education system. Ex: CBSE, Mangalore University', on_delete=django.db.models.deletion.CASCADE, to='nouns.governingbody')),
                ('paper_type', models.ForeignKey(help_text='Different levels of schools and colleges like Board and University', on_delete=django.db.models.deletion.CASCADE, to='nouns.papertype')),
                ('period', models.ForeignKey(help_text='different portion of the course like semisters or years', on_delete=django.db.models.deletion.CASCADE, to='nouns.period')),
                ('provider', models.ForeignKey(blank=True, default=1, help_text='The user who share the question paper', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('subject_name', models.ForeignKey(help_text='Question paper subject', on_delete=django.db.models.deletion.CASCADE, to='nouns.subject')),
            ],
        ),
    ]
