# Generated by Django 3.2 on 2021-05-26 05:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=10)),
                ('issues', models.TextField()),
                ('isuue_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Question_papers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_type', models.CharField(blank=True, choices=[('board', 'Board'), ('university', 'University')], max_length=12, null=True)),
                ('college', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('examination', models.CharField(max_length=100)),
                ('paper', models.FileField(upload_to='preqps')),
                ('slug', models.CharField(blank=True, max_length=400)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('provider', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('paper_type', models.CharField(blank=True, choices=[('board', 'Board'), ('university', 'University')], max_length=12, null=True)),
                ('board', models.CharField(max_length=100)),
                ('claass', models.CharField(max_length=100)),
                ('sem', models.CharField(max_length=100)),
                ('sub', models.CharField(max_length=100)),
                ('papertitle', models.CharField(max_length=100)),
                ('doc', models.FileField(upload_to='provider')),
                ('provide_date', models.DateTimeField(default=datetime.datetime.now)),
                ('name', models.ForeignKey(blank=True, default='user', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
