# Generated by Django 2.2.7 on 2020-05-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=10)),
                ('issues', models.TextField()),
                ('isuue_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('level', models.CharField(max_length=100)),
                ('board', models.CharField(max_length=100)),
                ('claass', models.CharField(max_length=100)),
                ('sem', models.CharField(max_length=100)),
                ('sub', models.CharField(max_length=100)),
                ('papertitle', models.CharField(max_length=100)),
                ('doc', models.FileField(upload_to='provider')),
                ('provide_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question_papers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('college', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('examination', models.CharField(max_length=100)),
                ('paper', models.FileField(upload_to='preqps')),
            ],
        ),
    ]
