# Generated by Django 2.2.7 on 2020-05-30 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_papers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='isuue_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
