# Generated by Django 3.2 on 2021-05-26 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_papers', '0003_auto_20210526_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='email',
        ),
    ]
