# Generated by Django 3.0.6 on 2020-06-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_papers', '0004_auto_20200614_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_papers',
            name='slug',
            field=models.TextField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
