# Generated by Django 3.0.6 on 2020-06-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_papers', '0005_question_papers_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_papers',
            name='slug',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
