# Generated by Django 3.2 on 2021-06-01 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_papers', '0005_rename_question_papers_question_paper'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Issues',
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
    ]
