# Generated by Django 3.2 on 2021-06-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_papers', '0006_auto_20210601_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_paper',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
