# Generated by Django 3.1.4 on 2021-01-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_papers', '0007_auto_20200623_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board_Question_papers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=100)),
                ('board', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('examination', models.CharField(max_length=100)),
                ('paper', models.FileField(upload_to='preqps')),
                ('slug', models.CharField(blank=True, max_length=400)),
            ],
        ),
    ]
