# Generated by Django 3.2 on 2021-07-21 12:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question_papers', '0007_alter_question_paper_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question_paper',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='question_paper',
            name='slug',
        ),
        migrations.AddField(
            model_name='question_paper',
            name='complete_ref',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='question_paper',
            name='college',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='question_paper',
            name='course',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='question_paper',
            name='paper',
            field=models.FileField(upload_to='allqps', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='question_paper',
            name='paper_type',
            field=models.CharField(choices=[('board', 'board'), ('university', 'university'), ('competitive', 'competitive')], default='board', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question_paper',
            name='provider',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question_paper',
            name='university',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='question_paper',
            name='year',
            field=models.DateField(),
        ),
    ]
