# Generated by Django 3.2 on 2021-07-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_papers', '0008_auto_20210721_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question_paper',
            old_name='college',
            new_name='course_name',
        ),
        migrations.RenameField(
            model_name='question_paper',
            old_name='course',
            new_name='governing_body',
        ),
        migrations.RenameField(
            model_name='question_paper',
            old_name='paper',
            new_name='paper_doc',
        ),
        migrations.RenameField(
            model_name='question_paper',
            old_name='examination',
            new_name='paper_title',
        ),
        migrations.RenameField(
            model_name='question_paper',
            old_name='year',
            new_name='paper_year',
        ),
        migrations.RenameField(
            model_name='question_paper',
            old_name='subject',
            new_name='subject_name',
        ),
        migrations.RemoveField(
            model_name='question_paper',
            name='university',
        ),
        migrations.AddField(
            model_name='question_paper',
            name='education_type',
            field=models.CharField(choices=[('sslc', 'sslc'), ('puc', 'puc'), ('degree', 'degree'), ('engineering', 'engineering'), ('diploma', 'diploma')], default='none', max_length=12),
        ),
        migrations.AddField(
            model_name='question_paper',
            name='period',
            field=models.CharField(choices=[('first', 'first'), ('second', 'second'), ('third', 'third'), ('fourth', 'fourth'), ('fifth', 'fifth'), ('sixth', 'sixth'), ('seventh', 'seventh'), ('eighth', 'eighth')], default='', max_length=12),
            preserve_default=False,
        ),
    ]
