# Generated by Django 3.2 on 2021-07-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_papers', '0009_auto_20210721_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_paper',
            name='education_type',
            field=models.CharField(choices=[('sslc', 'sslc'), ('puc', 'puc'), ('degree', 'degree'), ('engineering', 'engineering'), ('diploma', 'diploma')], max_length=12),
        ),
    ]
