# Generated by Django 3.1.4 on 2021-01-15 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question_papers', '0009_auto_20210115_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='level',
        ),
        migrations.AddField(
            model_name='provider',
            name='paper_type',
            field=models.CharField(blank=True, choices=[('board', 'Board'), ('university', 'University')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='question_papers',
            name='provider',
            field=models.ForeignKey(blank=True, default='user', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
