# Generated by Django 3.2 on 2021-07-22 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_papers', '0010_alter_question_paper_education_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='question_paper',
            name='course_name',
        ),
        migrations.CreateModel(
            name='GoverningBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('course_name', models.ManyToManyField(to='question_papers.Course')),
            ],
        ),
        migrations.AlterField(
            model_name='question_paper',
            name='governing_body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_papers.governingbody'),
        ),
    ]
