# Generated by Django 3.1.4 on 2021-02-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_papers', '0011_auto_20210131_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_papers',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
