# Generated by Django 3.2 on 2021-07-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_papers', '0011_auto_20210722_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='governingbody',
            name='course_name',
        ),
        migrations.AddField(
            model_name='question_paper',
            name='course_name',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='question_paper',
            name='education_type',
            field=models.CharField(choices=[('sslc', 'sslc'), ('puc', 'puc'), ('degree', 'degree'), ('engineering', 'engineering'), ('diploma', 'diploma')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='question_paper',
            name='governing_body',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='question_paper',
            name='period',
            field=models.CharField(choices=[('first', 'first'), ('second', 'second'), ('third', 'third'), ('fourth', 'fourth'), ('fifth', 'fifth'), ('sixth', 'sixth'), ('seventh', 'seventh'), ('eighth', 'eighth')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='question_paper',
            name='subject_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='GoverningBody',
        ),
    ]
