# Generated by Django 3.2 on 2021-07-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_papers', '0012_auto_20210722_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_paper',
            name='course_name',
            field=models.SlugField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='question_paper',
            name='education_type',
            field=models.SlugField(blank=True, choices=[('sslc', 'sslc'), ('puc', 'puc'), ('degree', 'degree'), ('engineering', 'engineering'), ('diploma', 'diploma')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='question_paper',
            name='governing_body',
            field=models.SlugField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='question_paper',
            name='paper_title',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question_paper',
            name='paper_type',
            field=models.SlugField(choices=[('board', 'board'), ('university', 'university'), ('competitive', 'competitive')], max_length=12),
        ),
        migrations.AlterField(
            model_name='question_paper',
            name='period',
            field=models.SlugField(blank=True, choices=[('first', 'first'), ('second', 'second'), ('third', 'third'), ('fourth', 'fourth'), ('fifth', 'fifth'), ('sixth', 'sixth'), ('seventh', 'seventh'), ('eighth', 'eighth')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='question_paper',
            name='subject_name',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
