# Generated by Django 3.2 on 2021-09-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_papers', '0013_auto_20210722_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_paper',
            name='period',
            field=models.SlugField(blank=True, choices=[('first', 'first'), ('second', 'second'), ('third', 'third'), ('fourth', 'fourth'), ('fifth', 'fifth'), ('sixth', 'sixth'), ('seventh', 'seventh'), ('eighth', 'eighth'), ('none', 'none')], max_length=12, null=True),
        ),
    ]
