# Generated by Django 3.2 on 2021-12-05 18:06

import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_papers', '0015_alter_question_paper_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_paper',
            name='paper_doc',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='allqps', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
