# Generated by Django 3.2.10 on 2021-12-24 17:21

import cloudinary_storage.storage
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question_papers', '0017_alter_question_paper_paper_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_paper',
            name='complete_ref',
            field=models.CharField(blank=True, help_text='a complete reference which is used in search', max_length=800),
        ),
        migrations.AlterField(
            model_name='question_paper',
            name='course_name',
            field=models.SlugField(default='board', help_text='Name of the course', max_length=800),
        ),
        migrations.AlterField(
            model_name='question_paper',
            name='education_type',
            field=models.SlugField(blank=True, choices=[('sslc', 'sslc'), ('puc', 'puc'), ('degree', 'degree'), ('engineering', 'engineering'), ('diploma', 'diploma')], help_text='Different education types like SSLC, PUC,Degree, Engineering or Diploma', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='question_paper',
            name='governing_body',
            field=models.SlugField(blank=True, help_text='The authority who governs that Education system. Ex: CBSE, Mangalore University', max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='question_paper',
            name='paper_doc',
            field=models.FileField(help_text='The actual paper documnet', storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='qpweb', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='question_paper',
            name='paper_title',
            field=models.SlugField(help_text='title of the paper', max_length=100),
        ),
        migrations.AlterField(
            model_name='question_paper',
            name='paper_type',
            field=models.SlugField(choices=[('board', 'board'), ('university', 'university'), ('competitive', 'competitive')], help_text='Different levels of schools and colleges like Board and University', max_length=12),
        ),
        migrations.AlterField(
            model_name='question_paper',
            name='paper_year',
            field=models.DateField(help_text='year when the question paper was released'),
        ),
        migrations.AlterField(
            model_name='question_paper',
            name='period',
            field=models.SlugField(blank=True, choices=[('first', 'first'), ('second', 'second'), ('third', 'third'), ('fourth', 'fourth'), ('fifth', 'fifth'), ('sixth', 'sixth'), ('seventh', 'seventh'), ('eighth', 'eighth'), ('none', 'none')], help_text='different portion of the course like semisters or years', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='question_paper',
            name='provider',
            field=models.ForeignKey(blank=True, default=1, help_text='The user who share the question paper', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question_paper',
            name='subject_name',
            field=models.SlugField(blank=True, help_text='Question paper subject', max_length=100, null=True),
        ),
    ]
