# Generated by Django 3.2.10 on 2022-01-29 18:14

import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models
import question_papers.models


class Migration(migrations.Migration):

    dependencies = [
        ('question_papers', '0019_alter_question_paper_paper_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_paper',
            name='paper_doc',
            field=models.FileField(help_text='The actual paper documnet', max_length=200, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=question_papers.models.update_filename_and_path_dev, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
