# Generated by Django 3.2 on 2021-09-03 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provides', '0004_alter_provide_paper_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provide',
            old_name='name',
            new_name='provider',
        ),
    ]
