# Generated by Django 3.2 on 2021-09-05 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provides', '0005_rename_name_provide_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='provide',
            name='paper_year',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='provide',
            name='college',
            field=models.CharField(blank=True, choices=[('sslc', 'SSLC'), ('puc', 'PUC'), ('degree', 'Degree'), ('engineering', 'Engineering'), ('diploma', 'Diploma'), ('iti', 'ITI')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='provide',
            name='paper_type',
            field=models.CharField(choices=[('board', 'Board'), ('university', 'University')], max_length=12),
        ),
        migrations.AlterField(
            model_name='provide',
            name='sem',
            field=models.CharField(blank=True, choices=[('first', 'first'), ('second', 'second'), ('third', 'third'), ('fourth', 'fourth'), ('fifth', 'fifth'), ('sixth', 'sixth'), ('seventh', 'seventh'), ('eighth', 'eighth')], max_length=100, null=True),
        ),
    ]
