# Generated by Django 3.2 on 2021-09-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provides', '0008_auto_20210910_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provide',
            name='period',
            field=models.CharField(choices=[('first', 'first'), ('second', 'second'), ('third', 'third'), ('fourth', 'fourth'), ('fifth', 'fifth'), ('sixth', 'sixth'), ('seventh', 'seventh'), ('eighth', 'eighth'), ('none', 'none')], max_length=12),
        ),
    ]
