# Generated by Django 3.2 on 2021-09-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provides', '0010_provide_provider_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provide',
            name='provided_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
