# Generated by Django 3.2 on 2021-12-04 17:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provides', '0011_alter_provide_provided_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provide',
            name='doc',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
