# Generated by Django 3.2 on 2021-12-05 15:25

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provides', '0014_alter_provide_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provide',
            name='doc',
            field=models.ImageField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='raw/provider'),
        ),
    ]
