# Generated by Django 4.1.7 on 2023-09-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("provides", "0019_alter_provide_doc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provide",
            name="paper_title",
            field=models.CharField(
                choices=[
                    ("final_examination", "Final Examination"),
                    ("reexamination", "Re-examination"),
                    ("model", "Model Question Paper"),
                ],
                max_length=100,
            ),
        ),
    ]
