# Generated by Django 3.2 on 2021-05-04 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Practice',
        ),
    ]
