# Generated by Django 3.1.4 on 2021-01-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0003_practice_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='college',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='../static/question_papers/images/user-circle.png', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='content',
            field=models.TextField(),
        ),
    ]
